void main()
{
  int reg_len = 288;
  int lenA = 93;
  int lenB = 84;
  int lenC = 111; 
  int stream_len = 300;
  __CPROVER_bool input[reg_len];
  __CPROVER_bool reg[reg_len];
  __CPROVER_bool stream[stream_len];
  __CPROVER_bool t1;
  __CPROVER_bool t2;
  __CPROVER_bool t3;
  int i;
  int j;

  /* Setting assume for all input bits (or some part of the bits) */

  int k = reg_len / 2;
  for (i = 0; i < k; i++)
    __CPROVER_assume(input[i] == 1);
  for (i = k; i < reg_len; i++)
    __CPROVER_assume(input[i] == 0);

  for (i = 0; i < reg_len; i++)
    reg[i] = input[i];

/* Performing LENSTREAM steps */ 
  for(i = 0; i < stream_len; i = i + 1) {
    stream[i] = reg[65]^reg[92]^reg[161]^reg[176]^reg[242]^reg[287];
	  t1 = reg[65]^reg[90]&reg[91]^reg[92]^reg[170];
	  t2 = reg[161]^reg[174]&reg[175]^reg[176]^reg[263];
	  t3 = reg[242]^reg[285]&reg[286]^reg[287]^reg[68];

	  for(j = lenA - 1; j > 0; j = j - 1)
	    reg[j] = reg[j-1];
	  reg[0] = t3;

	  for(j = lenA + lenB - 1; j > lenA; j = j - 1)
	    reg[j] = reg[j-1];
	  reg[lenA] = t1;

	  for(j = lenA + lenB + lenC - 1; j > lenA + lenB; j = j - 1)
	    reg[j] = reg[j-1];
	  reg[lenA + lenB] = t2;
  }

   /* Setting assume for all stream bits (or some part of the bits) */

__CPROVER_assume(stream[0] == 0);
__CPROVER_assume(stream[1] == 0);
__CPROVER_assume(stream[2] == 0);
__CPROVER_assume(stream[3] == 0);
__CPROVER_assume(stream[4] == 0);
__CPROVER_assume(stream[5] == 0);
__CPROVER_assume(stream[6] == 0);
__CPROVER_assume(stream[7] == 0);
__CPROVER_assume(stream[8] == 0);
__CPROVER_assume(stream[9] == 0);
__CPROVER_assume(stream[10] == 0);
__CPROVER_assume(stream[11] == 0);
__CPROVER_assume(stream[12] == 0);
__CPROVER_assume(stream[13] == 0);
__CPROVER_assume(stream[14] == 0);
__CPROVER_assume(stream[15] == 0);
__CPROVER_assume(stream[16] == 0);
__CPROVER_assume(stream[17] == 0);
__CPROVER_assume(stream[18] == 1);
__CPROVER_assume(stream[19] == 1);
__CPROVER_assume(stream[20] == 1);
__CPROVER_assume(stream[21] == 1);
__CPROVER_assume(stream[22] == 1);
__CPROVER_assume(stream[23] == 1);
__CPROVER_assume(stream[24] == 1);
__CPROVER_assume(stream[25] == 1);
__CPROVER_assume(stream[26] == 1);
__CPROVER_assume(stream[27] == 1);
__CPROVER_assume(stream[28] == 1);
__CPROVER_assume(stream[29] == 1);
__CPROVER_assume(stream[30] == 1);
__CPROVER_assume(stream[31] == 1);
__CPROVER_assume(stream[32] == 1);
__CPROVER_assume(stream[33] == 0);
__CPROVER_assume(stream[34] == 0);
__CPROVER_assume(stream[35] == 0);
__CPROVER_assume(stream[36] == 0);
__CPROVER_assume(stream[37] == 0);
__CPROVER_assume(stream[38] == 0);
__CPROVER_assume(stream[39] == 0);
__CPROVER_assume(stream[40] == 0);
__CPROVER_assume(stream[41] == 0);
__CPROVER_assume(stream[42] == 0);
__CPROVER_assume(stream[43] == 0);
__CPROVER_assume(stream[44] == 0);
__CPROVER_assume(stream[45] == 0);
__CPROVER_assume(stream[46] == 0);
__CPROVER_assume(stream[47] == 0);
__CPROVER_assume(stream[48] == 0);
__CPROVER_assume(stream[49] == 0);
__CPROVER_assume(stream[50] == 0);
__CPROVER_assume(stream[51] == 0);
__CPROVER_assume(stream[52] == 0);
__CPROVER_assume(stream[53] == 0);
__CPROVER_assume(stream[54] == 0);
__CPROVER_assume(stream[55] == 0);
__CPROVER_assume(stream[56] == 0);
__CPROVER_assume(stream[57] == 0);
__CPROVER_assume(stream[58] == 0);
__CPROVER_assume(stream[59] == 0);
__CPROVER_assume(stream[60] == 0);
__CPROVER_assume(stream[61] == 0);
__CPROVER_assume(stream[62] == 0);
__CPROVER_assume(stream[63] == 0);
__CPROVER_assume(stream[64] == 0);
__CPROVER_assume(stream[65] == 0);
__CPROVER_assume(stream[66] == 0);
__CPROVER_assume(stream[67] == 0);
__CPROVER_assume(stream[68] == 0);
__CPROVER_assume(stream[69] == 0);
__CPROVER_assume(stream[70] == 0);
__CPROVER_assume(stream[71] == 0);
__CPROVER_assume(stream[72] == 0);
__CPROVER_assume(stream[73] == 0);
__CPROVER_assume(stream[74] == 0);
__CPROVER_assume(stream[75] == 0);
__CPROVER_assume(stream[76] == 0);
__CPROVER_assume(stream[77] == 0);
__CPROVER_assume(stream[78] == 0);
__CPROVER_assume(stream[79] == 0);
__CPROVER_assume(stream[80] == 0);
__CPROVER_assume(stream[81] == 0);
__CPROVER_assume(stream[82] == 0);
__CPROVER_assume(stream[83] == 0);
__CPROVER_assume(stream[84] == 1);
__CPROVER_assume(stream[85] == 1);
__CPROVER_assume(stream[86] == 1);
__CPROVER_assume(stream[87] == 1);
__CPROVER_assume(stream[88] == 1);
__CPROVER_assume(stream[89] == 1);
__CPROVER_assume(stream[90] == 1);
__CPROVER_assume(stream[91] == 1);
__CPROVER_assume(stream[92] == 1);
__CPROVER_assume(stream[93] == 1);
__CPROVER_assume(stream[94] == 1);
__CPROVER_assume(stream[95] == 1);
__CPROVER_assume(stream[96] == 0);
__CPROVER_assume(stream[97] == 0);
__CPROVER_assume(stream[98] == 1);
__CPROVER_assume(stream[99] == 0);
__CPROVER_assume(stream[100] == 0);
__CPROVER_assume(stream[101] == 0);
__CPROVER_assume(stream[102] == 0);
__CPROVER_assume(stream[103] == 0);
__CPROVER_assume(stream[104] == 0);
__CPROVER_assume(stream[105] == 0);
__CPROVER_assume(stream[106] == 0);
__CPROVER_assume(stream[107] == 0);
__CPROVER_assume(stream[108] == 0);
__CPROVER_assume(stream[109] == 0);
__CPROVER_assume(stream[110] == 0);
__CPROVER_assume(stream[111] == 1);
__CPROVER_assume(stream[112] == 1);
__CPROVER_assume(stream[113] == 1);
__CPROVER_assume(stream[114] == 1);
__CPROVER_assume(stream[115] == 1);
__CPROVER_assume(stream[116] == 1);
__CPROVER_assume(stream[117] == 1);
__CPROVER_assume(stream[118] == 1);
__CPROVER_assume(stream[119] == 1);
__CPROVER_assume(stream[120] == 1);
__CPROVER_assume(stream[121] == 1);
__CPROVER_assume(stream[122] == 1);
__CPROVER_assume(stream[123] == 1);
__CPROVER_assume(stream[124] == 1);
__CPROVER_assume(stream[125] == 1);
__CPROVER_assume(stream[126] == 1);
__CPROVER_assume(stream[127] == 1);
__CPROVER_assume(stream[128] == 1);
__CPROVER_assume(stream[129] == 0);
__CPROVER_assume(stream[130] == 0);
__CPROVER_assume(stream[131] == 0);
__CPROVER_assume(stream[132] == 0);
__CPROVER_assume(stream[133] == 0);
__CPROVER_assume(stream[134] == 0);
__CPROVER_assume(stream[135] == 0);
__CPROVER_assume(stream[136] == 0);
__CPROVER_assume(stream[137] == 0);
__CPROVER_assume(stream[138] == 0);
__CPROVER_assume(stream[139] == 0);
__CPROVER_assume(stream[140] == 0);
__CPROVER_assume(stream[141] == 0);
__CPROVER_assume(stream[142] == 0);
__CPROVER_assume(stream[143] == 1);
__CPROVER_assume(stream[144] == 0);
__CPROVER_assume(stream[145] == 0);
__CPROVER_assume(stream[146] == 0);
__CPROVER_assume(stream[147] == 0);
__CPROVER_assume(stream[148] == 0);
__CPROVER_assume(stream[149] == 0);
__CPROVER_assume(stream[150] == 1);
__CPROVER_assume(stream[151] == 1);
__CPROVER_assume(stream[152] == 1);
__CPROVER_assume(stream[153] == 1);
__CPROVER_assume(stream[154] == 1);
__CPROVER_assume(stream[155] == 1);
__CPROVER_assume(stream[156] == 1);
__CPROVER_assume(stream[157] == 1);
__CPROVER_assume(stream[158] == 1);
__CPROVER_assume(stream[159] == 1);
__CPROVER_assume(stream[160] == 1);
__CPROVER_assume(stream[161] == 1);
__CPROVER_assume(stream[162] == 0);
__CPROVER_assume(stream[163] == 0);
__CPROVER_assume(stream[164] == 1);
__CPROVER_assume(stream[165] == 0);
__CPROVER_assume(stream[166] == 0);
__CPROVER_assume(stream[167] == 0);
__CPROVER_assume(stream[168] == 0);
__CPROVER_assume(stream[169] == 0);
__CPROVER_assume(stream[170] == 0);
__CPROVER_assume(stream[171] == 1);
__CPROVER_assume(stream[172] == 1);
__CPROVER_assume(stream[173] == 1);
__CPROVER_assume(stream[174] == 0);
__CPROVER_assume(stream[175] == 1);
__CPROVER_assume(stream[176] == 1);
__CPROVER_assume(stream[177] == 1);
__CPROVER_assume(stream[178] == 1);
__CPROVER_assume(stream[179] == 1);
__CPROVER_assume(stream[180] == 1);
__CPROVER_assume(stream[181] == 1);
__CPROVER_assume(stream[182] == 1);
__CPROVER_assume(stream[183] == 1);
__CPROVER_assume(stream[184] == 1);
__CPROVER_assume(stream[185] == 0);
__CPROVER_assume(stream[186] == 1);
__CPROVER_assume(stream[187] == 1);
__CPROVER_assume(stream[188] == 1);
__CPROVER_assume(stream[189] == 0);
__CPROVER_assume(stream[190] == 0);
__CPROVER_assume(stream[191] == 1);
__CPROVER_assume(stream[192] == 0);
__CPROVER_assume(stream[193] == 0);
__CPROVER_assume(stream[194] == 1);
__CPROVER_assume(stream[195] == 0);
__CPROVER_assume(stream[196] == 0);
__CPROVER_assume(stream[197] == 0);
__CPROVER_assume(stream[198] == 0);
__CPROVER_assume(stream[199] == 0);
__CPROVER_assume(stream[200] == 0);
__CPROVER_assume(stream[201] == 0);
__CPROVER_assume(stream[202] == 0);
__CPROVER_assume(stream[203] == 0);
__CPROVER_assume(stream[204] == 0);
__CPROVER_assume(stream[205] == 0);
__CPROVER_assume(stream[206] == 0);
__CPROVER_assume(stream[207] == 0);
__CPROVER_assume(stream[208] == 0);
__CPROVER_assume(stream[209] == 0);
__CPROVER_assume(stream[210] == 1);
__CPROVER_assume(stream[211] == 1);
__CPROVER_assume(stream[212] == 1);
__CPROVER_assume(stream[213] == 1);
__CPROVER_assume(stream[214] == 1);
__CPROVER_assume(stream[215] == 1);
__CPROVER_assume(stream[216] == 0);
__CPROVER_assume(stream[217] == 0);
__CPROVER_assume(stream[218] == 0);
__CPROVER_assume(stream[219] == 0);
__CPROVER_assume(stream[220] == 1);
__CPROVER_assume(stream[221] == 0);
__CPROVER_assume(stream[222] == 0);
__CPROVER_assume(stream[223] == 0);
__CPROVER_assume(stream[224] == 0);
__CPROVER_assume(stream[225] == 0);
__CPROVER_assume(stream[226] == 0);
__CPROVER_assume(stream[227] == 0);
__CPROVER_assume(stream[228] == 1);
__CPROVER_assume(stream[229] == 1);
__CPROVER_assume(stream[230] == 0);
__CPROVER_assume(stream[231] == 1);
__CPROVER_assume(stream[232] == 1);
__CPROVER_assume(stream[233] == 1);
__CPROVER_assume(stream[234] == 1);
__CPROVER_assume(stream[235] == 1);
__CPROVER_assume(stream[236] == 1);
__CPROVER_assume(stream[237] == 1);
__CPROVER_assume(stream[238] == 1);
__CPROVER_assume(stream[239] == 1);
__CPROVER_assume(stream[240] == 0);
__CPROVER_assume(stream[241] == 1);
__CPROVER_assume(stream[242] == 1);
__CPROVER_assume(stream[243] == 0);
__CPROVER_assume(stream[244] == 1);
__CPROVER_assume(stream[245] == 1);
__CPROVER_assume(stream[246] == 1);
__CPROVER_assume(stream[247] == 1);
__CPROVER_assume(stream[248] == 0);
__CPROVER_assume(stream[249] == 0);
__CPROVER_assume(stream[250] == 0);
__CPROVER_assume(stream[251] == 1);
__CPROVER_assume(stream[252] == 1);
__CPROVER_assume(stream[253] == 1);
__CPROVER_assume(stream[254] == 0);
__CPROVER_assume(stream[255] == 0);
__CPROVER_assume(stream[256] == 0);
__CPROVER_assume(stream[257] == 0);
__CPROVER_assume(stream[258] == 1);
__CPROVER_assume(stream[259] == 0);
__CPROVER_assume(stream[260] == 0);
__CPROVER_assume(stream[261] == 1);
__CPROVER_assume(stream[262] == 0);
__CPROVER_assume(stream[263] == 0);
__CPROVER_assume(stream[264] == 0);
__CPROVER_assume(stream[265] == 0);
__CPROVER_assume(stream[266] == 0);
__CPROVER_assume(stream[267] == 1);
__CPROVER_assume(stream[268] == 0);
__CPROVER_assume(stream[269] == 0);
__CPROVER_assume(stream[270] == 1);
__CPROVER_assume(stream[271] == 0);
__CPROVER_assume(stream[272] == 1);
__CPROVER_assume(stream[273] == 1);
__CPROVER_assume(stream[274] == 1);
__CPROVER_assume(stream[275] == 0);
__CPROVER_assume(stream[276] == 1);
__CPROVER_assume(stream[277] == 1);
__CPROVER_assume(stream[278] == 1);
__CPROVER_assume(stream[279] == 1);
__CPROVER_assume(stream[280] == 1);
__CPROVER_assume(stream[281] == 0);
__CPROVER_assume(stream[282] == 1);
__CPROVER_assume(stream[283] == 1);
__CPROVER_assume(stream[284] == 0);
__CPROVER_assume(stream[285] == 0);
__CPROVER_assume(stream[286] == 1);
__CPROVER_assume(stream[287] == 0);
__CPROVER_assume(stream[288] == 1);
__CPROVER_assume(stream[289] == 1);
__CPROVER_assume(stream[290] == 1);
__CPROVER_assume(stream[291] == 0);
__CPROVER_assume(stream[292] == 0);
__CPROVER_assume(stream[293] == 0);
__CPROVER_assume(stream[294] == 1);
__CPROVER_assume(stream[295] == 1);
__CPROVER_assume(stream[296] == 1);
__CPROVER_assume(stream[297] == 1);
__CPROVER_assume(stream[298] == 1);
__CPROVER_assume(stream[299] == 1);
  /* To generate the cbmc property */
  __CPROVER_assert(0,"test");
  return 0;
}
